# Тема “Вычисления с помощью Numpy”

## Задание 1
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.<br>
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.<br>
Будем считать, что каждый столбец - это признак, а строка - наблюдение.<br>
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.<br>
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [84]:
import numpy as np

In [85]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])
a=a.T
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [86]:
a_T = a.T
mean_a = []
for i in range(len(a_T)):
    mean_a.append(a_T[i].mean())
print(mean_a)

[2.0, 8.4]


In [87]:
# придумал короче и быстрее
mean_a=a.mean(axis = 0)
print(mean_a)

[2.  8.4]


## Задание 2
Вычислите массив a_centered,<br>
отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a.<br>
Вычисление должно производиться в одно действие.<br>
Получившийся массив должен иметь размер 5x2.

In [88]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


## Задание 3
Найдите скалярное произведение столбцов массива a_centered.<br>
В результате должна получиться величина _centered_spa.<br>
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [89]:
# так какая переменная то должна быть? _centered_spa или a_centered_sp ?
a_centered_T = a_centered.T
a_centered_sp = a_centered_T[0].dot(a_centered_T[1])
print(a_centered_sp)
N = len(a_centered)
answer = a_centered_sp/(N-1)
print(answer)

8.0
2.0


## Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся
в массиве “а”.<br>
В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N,<br>
поэтому полученная нами величина является несмещенной оценкой ковариации.<br>

В этом задании проверьте получившееся число,<br>
вычислив ковариацию еще одним способом - с помощью функции np.cov.<br>
В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”.<br>
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [90]:
# "В задании 4 мы делили ..." - всё-таки в задании 3!
cov = np.cov(a.T)
cov

array([[1. , 2. ],
       [2. , 4.3]])

In [91]:
cov[0][1]

2.0

In [92]:
answer == cov[0][1]

True

# Тема “Работа с данными в Pandas”

## Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd.<br>
Создайте датафрейм authors со столбцами author_id и author_name,<br>
в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].<br>
Затем создайте датафрейм book cо столбцами author_id, book_title и price,<br>
в которых соответственно содержатся данные:
[1, 1, 1, 2, 2, 3, 3],<br>
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']<br>
Нужны prices! [500, 400, 300, 350, 450, 600, 200]

In [93]:
import pandas as pd

In [94]:
dict_ = {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский'],
}

authors = pd.DataFrame(dict_)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [104]:
dict_ = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий',
                   'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [500, 400, 300, 350, 450, 600, 200],
}

book = pd.DataFrame(dict_)
book

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

## Задание 2
Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [96]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

## Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [97]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

## Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price.<br>
В датафрейме authors_stat должны быть четыре столбца:<br>
author_name, min_price, max_price и mean_price,<br>
в которых должны содержаться соответственно<br>
имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [98]:
groupby = authors_price.groupby("author_name")
min_price = groupby.agg({"price": "min"}).rename(columns={'price':'min_price'})
max_price = groupby.agg({"price": "max"}).rename(columns={'price':'max_price'})
mean_price = groupby.agg({"price": "mean"}).rename(columns={'price':'mean_price'})
authors_stat = pd.concat([min_price, max_price, mean_price], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         200        600       400.0
Тургенев           300        500       400.0
Чехов              350        450       400.0

## Задание 5**
Создайте новый столбец в датафрейме authors_price под названием cover,<br>
в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая.<br>
В этот столбец поместите данные из следующего списка:<br>
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].<br>
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака.<br>
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.<br>
Используйте для этого функцию pd.pivot_table.<br>
При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов.<br>
Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".<br>
Затем загрузите из этого файла датафрейм и назовите его book_info2.<br>
Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [99]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

In [100]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                           columns=['cover'], aggfunc=sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800

In [101]:
book_info.to_pickle('book_info.pkl')

In [102]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800

In [103]:
all(book_info==book_info2)

True